<?php

namespace PW\EvmeetBundle\Repository;

use \DateTime;
use DateTimeZone;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

	public function classicFind()

	{

		$date_now = new DateTime('NOW' ,new DateTimeZone('Europe/Paris'));
		$date_now->setTime(0, 0, 0);
			
		$qb =  $this->createQueryBuilder('a');

		$qb
		->where('a.dateInvitation >= :date')
			->setParameter('date', $date_now)
		->orderBy('a.dateInvitation', 'ASC')
		;

		return $qb
		->getQuery()
		->getResult()
		;

	}
}
