<?php

namespace PW\EvmeetBundle\Repository;

/**
 * RegistredUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistredUserRepository extends \Doctrine\ORM\EntityRepository
{
	public function select($id, $userId)
	{

		$qb =  $this->createQueryBuilder('r');

		
		$qb
		->Where('r.articleId = :id')
		->setParameter('id', $id)
		->andWhere('r.userId = :userId')
		->setParameter('userId', $userId)
		;

		return $qb
		->getQuery()
		->getOneOrNullResult()
		;
	}
}
