pw_evmeet_homepage:
    path:     /
    defaults:
        _controller: PWEvmeetBundle:Core:index

pw_evmeet_liste:
    path:     /liste
    defaults:
        _controller: PWEvmeetBundle:Core:liste

pw_evmeet_creation:
    path:     /creation
    defaults:
        _controller: PWEvmeetBundle:Core:creation

pw_evmeet_detail:
    path:     /detail/{id}
    defaults:
        _controller: PWEvmeetBundle:Core:detail
    requirements:
        id: \d*

pw_evmeet_profil:
    path:     /profil
    defaults:
        _controller: PWEvmeetBundle:Core:profil

pw_evmeet_delete:
    path:     /delete/{id}
    defaults:
        _controller: PWEvmeetBundle:Core:deleteArticle

pw_evmeet_inscription:
    path:     /inscription/{id}
    defaults:
        _controller: PWEvmeetBundle:Core:inscriptionArticle

pw_evmeet_desinscription:
    path:     /desinscription/{id}
    defaults:
        _controller: PWEvmeetBundle:Core:desinscriptionArticle




